Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -266,6 +266,12 @@ jobs:
         run: |
           helm upgrade --install workout ./fitplan-helm/charts/workout --wait
 
-      - name: Run connection test to fitplanfrontend
+      - name: Test frontend connection
         run: |
-          helm test fitplan-helm --logs
+          kubectl run curl-test --image=curlimages/curl:latest --restart=Never \
+            --command -- curl -f http://34.107.231.170/ ||
+            (echo "Connection to fitplanfrontend failed" && exit 1)
+
+      #- name: Run connection test to fitplanfrontend
+       # run: |
+        #  helm test fitplan-helm --logs
