Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -5,6 +5,16 @@ on:
     branches: [ "main" ]
   workflow_dispatch:
 
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
+
+env:
+  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+  GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
+  PROJECT_ID: ${{ secrets.PROJECT_ID }
+
 jobs:
   build-and-deploy:
     runs-on: ubuntu-latest
@@ -20,16 +30,14 @@ jobs:
           cache: maven
 
       - name: Build and push images using spring-boot:build-image
-        env:
-          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
         run: |
           mvn clean spring-boot:build-image -DskipTests
 
-      - name: Building and pushing fitplanfrontend
+      - name: Build and push fitplanfrontend
         run: |
-          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/fitplanfrontend:latest .
-          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
-          docker push ${{ secrets.DOCKER_USERNAME }}/fitplanfrontend:latest
+          docker build --no-cache -t ${{ env.DOCKER_USERNAME }}/fitplanfrontend:${{ github.sha }} .
+          echo ${{ env.DOCKER_PASSWORD }} | docker login -u ${{ env.DOCKER_USERNAME }} --password-stdin
+          docker push ${{ env.DOCKER_USERNAME }}/fitplanfrontend:${{ github.sha }}
         working-directory: fitplanfrontend
 
       - name: Google Cloud authentication
@@ -45,57 +53,13 @@ jobs:
 
       - name: Set up kubectl
         run: |
-          kubectl config use-context gke_${{ secrets.PROJECT_ID }}_europe-central2-a_fitplan
+          kubectl config use-context gke_${{ env.PROJECT_ID }}_europe-central2-a_fitplan
 
       - name: Set up Helm
         uses: azure/setup-helm@v3
 
 
-      #- name: Create GCE Persistent Disk for MySQL
-      # run: |
-      #  gcloud compute disks create mysql-disk --size=10Gi --zone=europe-central2-a
-
-
-
-      # Remove conflicting secrets (if necessary)
-      #  - name: Remove existing secrets
-      # run: |
-      #   kubectl delete secret fitplan-helm-secrets --ignore-not-found
-
-      #- name: Uninstall existing common-config
-      #  run: |
-      #    helm uninstall common-config || echo "common-config release does not exist."
-
-      - name: Deploy common-config
-        run: |
-          helm upgrade --install common-config ./fitplan-helm/charts/common-config --wait
-
-      #- name: Uninstall existing configserver
-      #  run: |
-      #    helm uninstall configserver || echo "configserver release does not exist."
-
-      - name: Deploy configserver
-        run: |
-          helm upgrade --install configserver ./fitplan-helm/charts/configserver --wait
-
-      #- name: Uninstall existing mysql
-      #  run: |
-      #    helm uninstall mysql || echo "mysql release does not exist."
-
-      #- name: Cleanup MySQL PVC and PV
-      #  run: |
-      #    kubectl delete pvc mysql-pvc --ignore-not-found
-      #    kubectl delete pv mysql-pv --ignore-not-found
-
-      #- name: Delete existing MySQL disk (if any)
-      #  run: |
-      #    if gcloud compute disks describe mysql-disk --zone=europe-central2-a > /dev/null 2>&1; then
-      #      gcloud compute disks delete mysql-disk --zone=europe-central2-a --quiet
-      #    else
-      #      echo "MySQL disk not found, skipping deletion."
-      #    fi
-
-      - name: Check if MySQL disk exists
+      - name: Check and create MySQL disk
         run: |
           if ! gcloud compute disks describe mysql-disk --zone=europe-central2-a > /dev/null 2>&1; then
             gcloud compute disks create mysql-disk --size=10Gi --zone=europe-central2-a
@@ -103,180 +67,58 @@ jobs:
             echo "MySQL disk already exists, skipping creation."
           fi
 
-      - name: Deploy mysql
+  deploy-services:
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        service:
+          - "common-config"
+          - "configserver"
+          - "mysql"
+          - "mongodb"
+          - "zookeeper"
+          - "broker"
+          - "kafka-ui"
+          - "schema-registry"
+          - "keycloak"
+          - "prometheus"
+          - "loki"
+          - "tempo"
+          - "grafana"
+          - "exercise"
+          - "fitplan-ingress"
+          - "fitplanfrontend"
+          - "gateway"
+          - "notification"
+          - "validation"
+          - "workout"
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Google Cloud authentication
+        uses: google-github-actions/auth@v2
+        with:
+          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
+
+      - name: Get GKE credentials
+        uses: google-github-actions/get-gke-credentials@v2
+        with:
+          cluster_name: 'fitplan'
+          location: 'europe-central2-a'
+
+      - name: Deploy ${{ matrix.service }}
         run: |
-          helm upgrade --install mysql ./fitplan-helm/charts/mysql --wait
-
-      #- name: Uninstall existing mongodb
-      #  run: |
-      #    helm uninstall mongodb || echo "mongodb release does not exist."
-
-      #- name: Cleanup existing MongoDB PVC and PV
-      #  run: |
-      #    kubectl delete pvc mongodb-pvc --ignore-not-found
-      #    kubectl delete pv mongodb-pv --ignore-not-found
-
-      - name: Deploy mongodb
-        run: |
-          helm upgrade --install mongodb ./fitplan-helm/charts/mongodb --wait
-
-      #- name: Uninstall existing keycloak-mysql
-      #  run: |
-      #    helm uninstall keycloak-mysql || echo "keycloak-mysql release does not exist."
-
-      #- name: Cleanup Keycloak-MySQL PVC and PV
-      #  run: |
-      #    kubectl delete pvc keycloak-mysql-pvc --ignore-not-found
-      #    kubectl delete pv keycloak-mysql-pv --ignore-not-found
-
-      - name: Deploy keycloak-mysql
-        run: |
-          helm upgrade --install keycloak-mysql ./fitplan-helm/charts/keycloak-mysql --wait
-
-      #- name: Uninstall existing zookeeper
-      #  run: |
-      #    helm uninstall zookeeper || echo "zookeeper release does not exist."
-
-      - name: Deploy zookeeper
-        run: |
-          helm upgrade --install zookeeper ./fitplan-helm/charts/zookeeper --wait
-
-      #- name: Uninstall existing broker
-      #  run: |
-      #    helm uninstall broker || echo "broker release does not exist."
-
-      - name: Deploy broker
-        run: |
-          helm upgrade --install broker ./fitplan-helm/charts/broker --wait
-
-      #- name: Uninstall existing kafka-ui
-      #  run: |
-      #    helm uninstall kafka-ui || echo "kafka-ui release does not exist."
-
-      - name: Deploy kafka-ui
-        run: |
-          helm upgrade --install kafka-ui ./fitplan-helm/charts/kafka-ui --wait
-
-      #- name: Uninstall existing schema-registry
-      #  run: |
-      #    helm uninstall schema-registry || echo "schema-registry release does not exist."
-
-      - name: Deploy schema-registry
-        run: |
-          helm upgrade --install schema-registry ./fitplan-helm/charts/schema-registry --wait
-
-      #- name: Uninstall existing keycloak
-      #  run: |
-      #    helm uninstall keycloak || echo "keycloak release does not exist."
-
-      - name: Deploy keycloak
-        run: |
-          helm upgrade --install keycloak ./fitplan-helm/charts/keycloak --wait
-
-      #- name: Uninstall existing prometheus
-      #  run: |
-      #    helm uninstall prometheus || echo "prometheus release does not exist."
-
-      - name: Deploy prometheus
-        run: |
-          helm upgrade --install prometheus ./fitplan-helm/charts/prometheus --wait
-
-      #- name: Uninstall existing loki
-      #  run: |
-      #    helm uninstall loki || echo "loki release does not exist."
-
-      - name: Deploy loki
-        run: |
-          helm upgrade --install loki ./fitplan-helm/charts/loki --wait
-
-      #- name: Uninstall existing tempo
-      #  run: |
-      #    helm uninstall tempo || echo "tempo release does not exist."
-
-      #- name: Cleanup Tempo PVC and PV
-      #  run: |
-      #    kubectl delete pvc tempo-pvc --ignore-not-found
-      #    kubectl delete pv tempo-pv --ignore-not-found
-
-      - name: Deploy tempo
-        run: |
-          helm upgrade --install tempo ./fitplan-helm/charts/tempo --wait
-
-      #- name: Uninstall existing grafana
-      #  run: |
-      #    helm uninstall grafana || echo "grafana release does not exist."
-
-      - name: Deploy grafana
-        run: |
-          helm upgrade --install grafana ./fitplan-helm/charts/grafana --wait
-
-      #- name: Uninstall existing exercise
-      #  run: |
-      #    helm uninstall exercise || echo "exercise release does not exist."
-
-      - name: Deploy exercise
-        run: |
-          helm upgrade --install exercise ./fitplan-helm/charts/exercise --wait
-
-      #- name: Uninstall existing fitplan-ingress
-      #  run: |
-      #    helm uninstall fitplan-ingress || echo "fitplan-ingress release does not exist."
-
-      - name: Deploy fitplan-ingress
-        run: |
-          helm upgrade --install fitplan-ingress ./fitplan-helm/charts/fitplan-ingress --wait
-
-      #- name: Uninstall existing fitplanfrontend
-      #  run: |
-      #    helm uninstall fitplanfrontend || echo "fitplanfrontend release does not exist."
-
-      - name: Deploy fitplanfrontend
-        run: |
-          helm upgrade --install fitplanfrontend ./fitplan-helm/charts/fitplanfrontend --wait
-
-      #- name: Uninstall existing gateway
-      #  run: |
-      #    helm uninstall gateway || echo "gateway release does not exist."
-
-      - name: Deploy gateway
-        run: |
-          helm upgrade --install gateway ./fitplan-helm/charts/gateway --wait
-
-      #- name: Uninstall existing notification
-      #  run: |
-      #    helm uninstall notification || echo "notification release does not exist."
-
-      - name: Deploy notification
-        run: |
-          helm upgrade --install notification ./fitplan-helm/charts/notification --wait
-
-      #- name: Uninstall existing validation
-      #  run: |
-      #    helm uninstall validation || echo "validation release does not exist."
-
-      - name: Deploy validation
-        run: |
-          helm upgrade --install validation ./fitplan-helm/charts/validation --wait
-
-      #- name: Uninstall existing workout
-      #  run: |
-      #    helm uninstall workout || echo "workout release does not exist."
-
-      - name: Deploy workout
-        run: |
-          helm upgrade --install workout ./fitplan-helm/charts/workout --wait
-
-      #- name: Run curl test
-      #  run: |
-       #   # Delete the pod if it exists
-       #   kubectl delete pod curl-test --ignore-not-found
-        #  # Run the curl test pod
-         # kubectl run curl-test --image=curlimages/curl:latest --restart=Never -- \
-          #  curl -f http://34.107.231.170/ || (echo "Connection to fitplanfrontend failed" && exit 1)
-          # Fetch logs to verify the output
-         # kubectl logs curl-test
-          # Clean up the test pod
-        #  kubectl delete pod curl-test --ignore-not-found
+          retries=3
+          for ((i=1; i<=retries; i++)); do
+            if helm upgrade --install ${{ matrix.service }} ./fitplan-helm/charts/${{ matrix.service }} --wait --timeout 300s; then
+              break
+            elif [ "$i" -eq "$retries" ]; then
+              echo "Helm command failed after $retries attempts for ${{ matrix.service }}."
+              exit 1
+            fi
+            sleep 10
+          done
 
       - name: Test FitPlan Frontend via Public IP
         run: |
@@ -285,7 +127,9 @@ jobs:
             && echo "FitPlan frontend is reachable!" \
             || (echo "FitPlan frontend check failed" && exit 1)
 
-          
-      #- name: Run connection test to fitplanfrontend
-       # run: |
-        #  helm test fitplan-helm --logs
+      - name: Upload deployment logs
+        uses: actions/upload-artifact@v3
+        with:
+          name: deployment-logs
+          path: ./logs/
+
