Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -50,36 +50,12 @@ jobs:
       - name: Set up Helm
         uses: azure/setup-helm@v3
 
-      - name: Cleanup MySQL PVC and PV
-        run: |
-          kubectl delete pvc mysql-pvc --ignore-not-found
-          kubectl delete pv mysql-pv --ignore-not-found
-          
-      - name: Cleanup existing MongoDB PVC and PV
-        run: |
-          kubectl delete pvc mongodb-pvc --ignore-not-found
-          kubectl delete pv mongodb-pv --ignore-not-found
-
 
     #- name: Create GCE Persistent Disk for MySQL
      # run: |
       #  gcloud compute disks create mysql-disk --size=10Gi --zone=europe-central2-a
 
-      - name: Delete existing MySQL disk (if any)
-        run: |
-          if gcloud compute disks describe mysql-disk --zone=europe-central2-a > /dev/null 2>&1; then
-            gcloud compute disks delete mysql-disk --zone=europe-central2-a --quiet
-          else
-            echo "MySQL disk not found, skipping deletion."
-          fi
 
-      - name: Check if MySQL disk exists
-        run: |
-          if ! gcloud compute disks describe mysql-disk --zone=europe-central2-a > /dev/null 2>&1; then
-            gcloud compute disks create mysql-disk --size=10Gi --zone=europe-central2-a
-          else
-            echo "MySQL disk already exists, skipping creation."
-          fi
 
       # Remove conflicting secrets (if necessary)
     #  - name: Remove existing secrets
@@ -106,6 +82,27 @@ jobs:
         run: |
           helm uninstall mysql || echo "mysql release does not exist."
 
+      - name: Cleanup MySQL PVC and PV
+        run: |
+          kubectl delete pvc mysql-pvc --ignore-not-found
+          kubectl delete pv mysql-pv --ignore-not-found
+
+      - name: Delete existing MySQL disk (if any)
+        run: |
+          if gcloud compute disks describe mysql-disk --zone=europe-central2-a > /dev/null 2>&1; then
+            gcloud compute disks delete mysql-disk --zone=europe-central2-a --quiet
+          else
+            echo "MySQL disk not found, skipping deletion."
+          fi
+
+      - name: Check if MySQL disk exists
+        run: |
+          if ! gcloud compute disks describe mysql-disk --zone=europe-central2-a > /dev/null 2>&1; then
+            gcloud compute disks create mysql-disk --size=10Gi --zone=europe-central2-a
+          else
+            echo "MySQL disk already exists, skipping creation."
+          fi
+
       - name: Deploy mysql
         run: |
           helm install mysql ./fitplan-helm/charts/mysql --wait
@@ -113,6 +110,11 @@ jobs:
       - name: Uninstall existing mongodb
         run: |
           helm uninstall mongodb || echo "mongodb release does not exist."
+
+      - name: Cleanup existing MongoDB PVC and PV
+        run: |
+          kubectl delete pvc mongodb-pvc --ignore-not-found
+          kubectl delete pv mongodb-pv --ignore-not-found
 
       - name: Deploy mongodb
         run: |
